// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoLog.proto
// Protobuf C++ Version: 5.30.0-dev

#ifndef ProtoLog_2eproto_2epb_2eh
#define ProtoLog_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5030000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_ProtoLog_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_ProtoLog_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_ProtoLog_2eproto;
class ProtoLog;
struct ProtoLogDefaultTypeInternal;
extern ProtoLogDefaultTypeInternal _ProtoLog_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ProtoLog_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class ProtoLog final
    : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:ProtoLog) */ {
 public:
  inline ProtoLog() : ProtoLog(nullptr) {}
  ~ProtoLog() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ProtoLog* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ProtoLog));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ProtoLog(
      ::google::protobuf::internal::ConstantInitialized);

  inline ProtoLog(const ProtoLog& from) : ProtoLog(nullptr, from) {}
  inline ProtoLog(ProtoLog&& from) noexcept
      : ProtoLog(nullptr, std::move(from)) {}
  inline ProtoLog& operator=(const ProtoLog& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtoLog& operator=(ProtoLog&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtoLog& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProtoLog* internal_default_instance() {
    return reinterpret_cast<const ProtoLog*>(
        &_ProtoLog_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ProtoLog& a, ProtoLog& b) { a.Swap(&b); }
  inline void Swap(ProtoLog* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtoLog* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtoLog* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ProtoLog>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ProtoLog& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ProtoLog& from) { ProtoLog::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ProtoLog* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "ProtoLog"; }

 protected:
  explicit ProtoLog(::google::protobuf::Arena* arena);
  ProtoLog(::google::protobuf::Arena* arena, const ProtoLog& from);
  ProtoLog(::google::protobuf::Arena* arena, ProtoLog&& from) noexcept
      : ProtoLog(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLogDateFieldNumber = 1,
    kLogSeverityFieldNumber = 2,
    kLogMessageFieldNumber = 3,
  };
  // string log_date = 1;
  void clear_log_date() ;
  const std::string& log_date() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_log_date(Arg_&& arg, Args_... args);
  std::string* mutable_log_date();
  PROTOBUF_NODISCARD std::string* release_log_date();
  void set_allocated_log_date(std::string* value);

  private:
  const std::string& _internal_log_date() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_log_date(
      const std::string& value);
  std::string* _internal_mutable_log_date();

  public:
  // string log_severity = 2;
  void clear_log_severity() ;
  const std::string& log_severity() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_log_severity(Arg_&& arg, Args_... args);
  std::string* mutable_log_severity();
  PROTOBUF_NODISCARD std::string* release_log_severity();
  void set_allocated_log_severity(std::string* value);

  private:
  const std::string& _internal_log_severity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_log_severity(
      const std::string& value);
  std::string* _internal_mutable_log_severity();

  public:
  // string log_message = 3;
  void clear_log_message() ;
  const std::string& log_message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_log_message(Arg_&& arg, Args_... args);
  std::string* mutable_log_message();
  PROTOBUF_NODISCARD std::string* release_log_message();
  void set_allocated_log_message(std::string* value);

  private:
  const std::string& _internal_log_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_log_message(
      const std::string& value);
  std::string* _internal_mutable_log_message();

  public:
  // @@protoc_insertion_point(class_scope:ProtoLog)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      48, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const ProtoLog& from_msg);
    ::google::protobuf::internal::ArenaStringPtr log_date_;
    ::google::protobuf::internal::ArenaStringPtr log_severity_;
    ::google::protobuf::internal::ArenaStringPtr log_message_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProtoLog_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ProtoLog_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ProtoLog

// string log_date = 1;
inline void ProtoLog::clear_log_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_date_.ClearToEmpty();
}
inline const std::string& ProtoLog::log_date() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ProtoLog.log_date)
  return _internal_log_date();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ProtoLog::set_log_date(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_date_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ProtoLog.log_date)
}
inline std::string* ProtoLog::mutable_log_date() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_log_date();
  // @@protoc_insertion_point(field_mutable:ProtoLog.log_date)
  return _s;
}
inline const std::string& ProtoLog::_internal_log_date() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.log_date_.Get();
}
inline void ProtoLog::_internal_set_log_date(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_date_.Set(value, GetArena());
}
inline std::string* ProtoLog::_internal_mutable_log_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.log_date_.Mutable( GetArena());
}
inline std::string* ProtoLog::release_log_date() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ProtoLog.log_date)
  return _impl_.log_date_.Release();
}
inline void ProtoLog::set_allocated_log_date(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_date_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.log_date_.IsDefault()) {
    _impl_.log_date_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoLog.log_date)
}

// string log_severity = 2;
inline void ProtoLog::clear_log_severity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_severity_.ClearToEmpty();
}
inline const std::string& ProtoLog::log_severity() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ProtoLog.log_severity)
  return _internal_log_severity();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ProtoLog::set_log_severity(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_severity_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ProtoLog.log_severity)
}
inline std::string* ProtoLog::mutable_log_severity() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_log_severity();
  // @@protoc_insertion_point(field_mutable:ProtoLog.log_severity)
  return _s;
}
inline const std::string& ProtoLog::_internal_log_severity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.log_severity_.Get();
}
inline void ProtoLog::_internal_set_log_severity(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_severity_.Set(value, GetArena());
}
inline std::string* ProtoLog::_internal_mutable_log_severity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.log_severity_.Mutable( GetArena());
}
inline std::string* ProtoLog::release_log_severity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ProtoLog.log_severity)
  return _impl_.log_severity_.Release();
}
inline void ProtoLog::set_allocated_log_severity(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_severity_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.log_severity_.IsDefault()) {
    _impl_.log_severity_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoLog.log_severity)
}

// string log_message = 3;
inline void ProtoLog::clear_log_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_message_.ClearToEmpty();
}
inline const std::string& ProtoLog::log_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:ProtoLog.log_message)
  return _internal_log_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ProtoLog::set_log_message(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:ProtoLog.log_message)
}
inline std::string* ProtoLog::mutable_log_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_log_message();
  // @@protoc_insertion_point(field_mutable:ProtoLog.log_message)
  return _s;
}
inline const std::string& ProtoLog::_internal_log_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.log_message_.Get();
}
inline void ProtoLog::_internal_set_log_message(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_message_.Set(value, GetArena());
}
inline std::string* ProtoLog::_internal_mutable_log_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.log_message_.Mutable( GetArena());
}
inline std::string* ProtoLog::release_log_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:ProtoLog.log_message)
  return _impl_.log_message_.Release();
}
inline void ProtoLog::set_allocated_log_message(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.log_message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.log_message_.IsDefault()) {
    _impl_.log_message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:ProtoLog.log_message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // ProtoLog_2eproto_2epb_2eh
