// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: ProtoLog.proto
// Protobuf C++ Version: 5.30.0-dev

#include "../include/ProtoLog.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ProtoLog::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : log_date_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        log_severity_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        log_message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ProtoLog::ProtoLog(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ProtoLog_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ProtoLogDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProtoLogDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProtoLogDefaultTypeInternal() {}
  union {
    ProtoLog _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProtoLogDefaultTypeInternal _ProtoLog_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ProtoLog_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ProtoLog_2eproto = nullptr;
const ::uint32_t
    TableStruct_ProtoLog_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ProtoLog, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ProtoLog, _impl_.log_date_),
        PROTOBUF_FIELD_OFFSET(::ProtoLog, _impl_.log_severity_),
        PROTOBUF_FIELD_OFFSET(::ProtoLog, _impl_.log_message_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ProtoLog)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_ProtoLog_default_instance_._instance,
};
const char descriptor_table_protodef_ProtoLog_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016ProtoLog.proto\"G\n\010ProtoLog\022\020\n\010log_date"
    "\030\001 \001(\t\022\024\n\014log_severity\030\002 \001(\t\022\023\n\013log_mess"
    "age\030\003 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_ProtoLog_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_ProtoLog_2eproto = {
    false,
    false,
    97,
    descriptor_table_protodef_ProtoLog_2eproto,
    "ProtoLog.proto",
    &descriptor_table_ProtoLog_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_ProtoLog_2eproto::offsets,
    file_level_enum_descriptors_ProtoLog_2eproto,
    file_level_service_descriptors_ProtoLog_2eproto,
};
// ===================================================================

class ProtoLog::_Internal {
 public:
};

ProtoLog::ProtoLog(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProtoLog_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ProtoLog)
}
inline PROTOBUF_NDEBUG_INLINE ProtoLog::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::ProtoLog& from_msg)
      : log_date_(arena, from.log_date_),
        log_severity_(arena, from.log_severity_),
        log_message_(arena, from.log_message_),
        _cached_size_{0} {}

ProtoLog::ProtoLog(
    ::google::protobuf::Arena* arena,
    const ProtoLog& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ProtoLog_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ProtoLog* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:ProtoLog)
}
inline PROTOBUF_NDEBUG_INLINE ProtoLog::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : log_date_(arena),
        log_severity_(arena),
        log_message_(arena),
        _cached_size_{0} {}

inline void ProtoLog::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ProtoLog::~ProtoLog() {
  // @@protoc_insertion_point(destructor:ProtoLog)
  SharedDtor(*this);
}
inline void ProtoLog::SharedDtor(MessageLite& self) {
  ProtoLog& this_ = static_cast<ProtoLog&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.log_date_.Destroy();
  this_._impl_.log_severity_.Destroy();
  this_._impl_.log_message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ProtoLog::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ProtoLog(arena);
}
constexpr auto ProtoLog::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ProtoLog),
                                            alignof(ProtoLog));
}
constexpr auto ProtoLog::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ProtoLog_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ProtoLog::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ProtoLog>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ProtoLog::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ProtoLog>(), &ProtoLog::ByteSizeLong,
              &ProtoLog::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ProtoLog, _impl_._cached_size_),
          false,
      },
      &ProtoLog::kDescriptorMethods,
      &descriptor_table_ProtoLog_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
        ProtoLog_class_data_ =
            ProtoLog::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* ProtoLog::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ProtoLog_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ProtoLog_class_data_.tc_table);
  return ProtoLog_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 48, 2> ProtoLog::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    ProtoLog_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ProtoLog>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string log_date = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ProtoLog, _impl_.log_date_)}},
    // string log_severity = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ProtoLog, _impl_.log_severity_)}},
    // string log_message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(ProtoLog, _impl_.log_message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string log_date = 1;
    {PROTOBUF_FIELD_OFFSET(ProtoLog, _impl_.log_date_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string log_severity = 2;
    {PROTOBUF_FIELD_OFFSET(ProtoLog, _impl_.log_severity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string log_message = 3;
    {PROTOBUF_FIELD_OFFSET(ProtoLog, _impl_.log_message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\10\10\14\13\0\0\0\0"
    "ProtoLog"
    "log_date"
    "log_severity"
    "log_message"
  }},
};

PROTOBUF_NOINLINE void ProtoLog::Clear() {
// @@protoc_insertion_point(message_clear_start:ProtoLog)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.log_date_.ClearToEmpty();
  _impl_.log_severity_.ClearToEmpty();
  _impl_.log_message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ProtoLog::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ProtoLog& this_ = static_cast<const ProtoLog&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ProtoLog::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ProtoLog& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ProtoLog)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string log_date = 1;
          if (!this_._internal_log_date().empty()) {
            const std::string& _s = this_._internal_log_date();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ProtoLog.log_date");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string log_severity = 2;
          if (!this_._internal_log_severity().empty()) {
            const std::string& _s = this_._internal_log_severity();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ProtoLog.log_severity");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string log_message = 3;
          if (!this_._internal_log_message().empty()) {
            const std::string& _s = this_._internal_log_message();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "ProtoLog.log_message");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ProtoLog)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ProtoLog::ByteSizeLong(const MessageLite& base) {
          const ProtoLog& this_ = static_cast<const ProtoLog&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ProtoLog::ByteSizeLong() const {
          const ProtoLog& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ProtoLog)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string log_date = 1;
            if (!this_._internal_log_date().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_log_date());
            }
            // string log_severity = 2;
            if (!this_._internal_log_severity().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_log_severity());
            }
            // string log_message = 3;
            if (!this_._internal_log_message().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_log_message());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ProtoLog::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ProtoLog*>(&to_msg);
  auto& from = static_cast<const ProtoLog&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProtoLog)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_log_date().empty()) {
    _this->_internal_set_log_date(from._internal_log_date());
  }
  if (!from._internal_log_severity().empty()) {
    _this->_internal_set_log_severity(from._internal_log_severity());
  }
  if (!from._internal_log_message().empty()) {
    _this->_internal_set_log_message(from._internal_log_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ProtoLog::CopyFrom(const ProtoLog& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProtoLog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ProtoLog::InternalSwap(ProtoLog* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.log_date_, &other->_impl_.log_date_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.log_severity_, &other->_impl_.log_severity_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.log_message_, &other->_impl_.log_message_, arena);
}

::google::protobuf::Metadata ProtoLog::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_ProtoLog_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
